spring.application.name=com.samvidhan.backend
spring.datasource.url=jdbc:mysql://localhost:3306/samvidhan_db
spring.datasource.username=root
spring.datasource.password=Nikhil6757999@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080